name: RBC460 Tracker
on:
  schedule:
    - cron: '0 23 * * *' # каждый день в 23:00 по UTC-5 (Торонто)
  workflow_dispatch:

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install pandas openpyxl selenium

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v1

      - name: Run tracker
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: |
          python tracker.py

      - name: Upload Excel
        uses: actions/upload-artifact@v4
        with:
          name: rbc460_prices
          path: rbc460_prices.xlsx

